### ISSUE TITLE
Wireless Tags

### ISSUE THREAD

**Issue by mapallatroni** [bhazer/Hubitat#3]
Not sure if you are still supporting this.  I installed it, seems to work as expected; however I get massive errors (maybe 20 identical email notifications) every 15 minutes.  Messages seem to rotate between my different tags:

app:382020-11-13 07:44:26.107 pm traceurl callback
app:382020-11-13 07:44:25.971 pm errorjava.lang.NumberFormatException: empty String on line 68 (handleUrlCallback)
app:382020-11-13 07:44:25.936 pm debugGenerating AppDebug Event: [name:appdebug, descriptionText:url callback: [access_token:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX, batteryVolt:2.87971, cap:, id:0, lux:0, name:Tag A - Frig, temperature:6.80267453193665, type:update], displayed:true]**
app:382020-11-13 07:44:25.929 pm traceurl callback
app:382020-11-13 07:40:01.067 pm tracesuccess
app:382020-11-13 07:40:00.123 pm tracesending /ethClient.asmx/GetTagList
app:382020-11-13 07:40:00.108 pm tracepollHandler

Thanks.

**Comment by bhazer** [comment]
Hmmm. Do you have tags that don't measure humidity? I guess nobody has run this with those tags before. Should be an easy fix. I'll try to get around to it this weekend.

**Comment by mapallatroni** [comment]
Correct - I have 3 of the regular tags which do not have humidity.  I was hoping it would be something easy :)

Thanks.

___________________
Michael P

**Comment by bhazer** [comment]
Ok. It should be fixed now, but I don't have a great way to test it.

**Comment by mapallatroni** [comment]
Thanks.  I will install and let you know.   Probably won’t be until tomorrow.

___________________
Michael P

**Comment by mapallatroni** [comment]
Here is a snippet of the log:

2020-11-15 08:04:51.222 pm errorgroovy.lang.MissingMethodException: No signature of method: java.math.BigDecimal.isDouble() is applicable for argument types: () values: []
Possible solutions: toDouble(), scale() on line 48 (updated)
app:382020-11-15 08:04:51.137 pm tracesuccess
app:382020-11-15 08:04:50.672 pm tracesending /ethClient.asmx/GetTagList
app:382020-11-15 08:04:50.662 pm tracepollHandler

___________________
Michael P

**Comment by mapallatroni** [comment]
The fix seems to have broken it completely.  It worked before despite the errors.
Here is another log snippet:

app:382020-11-16 07:01:59.334 am errorjava.lang.NullPointerException: null on line 72 (handleUrlCallback)
app:382020-11-16 07:01:59.298 am debugGenerating AppDebug Event: [name:appdebug, descriptionText:url callback: [access_token:b0a527f1-8988-4244-8365-33fd5df295eb, batteryVolt:2.923762, cap:, id:1, lux:0, name:Tag B - Wine Frig, temperature:15.3188743591309, type:update], displayed:true]
app:382020-11-16 07:01:59.292 am traceurl callback

___________________
Michael P

**Comment by bhazer** [comment]
5 months later and I think I've finally fixed this.
